version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: source/conf.py

formats:
  - pdf
# - epub  # Uncomment to include ePub format

python:
  install:
    - requirements: requirements.txt